CC=c99

all: single2 single3 find_period

single2: single_set_v4squared.c
	$(CC) -o ../single2 single_set_v4squared.c 

single3: single_set_v4cubed.c
	$(CC) -o ../single3 single_set_v4cubed.c

find_period: find_period.c
	$(CC) -o ../find_period find_period.c
